# Generated by Django 3.1.5 on 2022-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pages', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=150, unique=True)),
                ('base', models.ManyToManyField(related_name='products', to='core.BookJournalBase')),
            ],
        ),
    ]
