# Generated by Django 3.1.5 on 2022-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='base',
            field=models.ManyToManyField(related_name='books', to='core.BookJournalBase'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bullet', 'Bullet'), ('Food', 'Food'), ('Travel', 'Travel'), ('Sport', 'Sport')], max_length=10)),
                ('publisher', models.CharField(max_length=150, unique=True)),
                ('base', models.ManyToManyField(related_name='journals', to='core.BookJournalBase')),
            ],
        ),
    ]
